### PR TITLE
ci: set only image name as lowercase, leave image tag untouched

### PR DESCRIPTION
**Pull request by pchila**
Change image name to lowercase but leave the optional tag untouched

Signed-off-by: Paolo Chila <paolo.chila@dynatrace.com>

### CODE REVIEW

**Comment by christian-kreuzberger-dtx** [comment]
@Raffy23 what's your take on this?

IMO we are now fixing the fix for the fix of "uppercase names in Docker image names", which we seem to be preventing in keptn-service-template-go anyway:
image

image

image


I would prefer to not fix this issue, but revert to the original implementation (which was changed with this PR):
https://github.com/keptn/gh-automation/pull/15/files

**Comment by Raffy23** [comment]
We can revert to the previous implementation, until we find a better way of normalizing tags. I'm currently not sure what kind of unintended behavior is introduced by this change (e.g.: A registry with a port will probably not work anymore). But if we do, we also have to document somewhere that GitHub accounts with any uppercase letters can not use this action + any other action that depends on it ...

**Comment by christian-kreuzberger-dtx** [comment]
Reverting to the old behavior of not checking the input would break configurations that use
```
        TAGS: |
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE }}:${{ env.VERSION }}
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE }}:${{ env.VERSION }}.${{ env.DATETIME }}
```
which would require us to change the README.

Also, I just looked at service-template, we will also break it there, because I only tested it with upper case service name, but not repository/organization owner :(

```
          TAGS: |
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE }}:${{ env.VERSION }}
```

I digged a little bit deeper, and found a [Troubleshooting guide of build-push-action](https://github.com/docker/build-push-action/blob/master/TROUBLESHOOTING.md#repository-name-must-be-lowercase), which provides another example of fixing this:

```
- name: Sanitize repo slug
  uses: actions/github-script@v4
  id: repo_slug
  with:
    result-encoding: string
    script: return 'ghcr.io/${{ github.repository }}'.toLowerCase()

- name: Build and push
  uses: docker/build-push-action@v2
  with:
    context: .
    push: true
    tags: ${{ steps.repo_slug.outputs.result }}:latest
```

Nevertheless, I'm seeing many problems appear with uppercased names on GitHub repos vs. GHCR, therefore I'm willing to accept this PR for now (it doesn't make it worse, it improves the 99% case/golden path, it just doesn't solve all edge cases).

I will provide an issue in keptn-service-template-go to handle upper-case owner names better.

**Review by christian-kreuzberger-dtx — APPROVED** [review]
LGTM (see comment above)

**Pull request merged**
